### ISSUE TITLE
Category in Post Grid Not Inheriting Typography

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#148]
By default Otter adds a style to category h6 which overwrites the default theme h6 definition. 

http://snpy.in/cEWq9M

We don't need to add any font size for any h1-6 as those are defined in the theme level and will break the overall consistency with the layout

**Comment by HardeepAsrani** [comment]
@selul It's done to have a particular style. If I remove the typography, it will go from looking like this:

<img width="621" alt="Screen Shot 2019-12-23 at 12 55 13 AM" src="https://user-images.githubusercontent.com/2649903/71326311-f94c5f80-251e-11ea-85b0-214af6f87525.png">

to look like this:

<img width="642" alt="Screen Shot 2019-12-23 at 12 55 08 AM" src="https://user-images.githubusercontent.com/2649903/71326312-fe111380-251e-11ea-80d0-309604830c14.png">

**Comment by selul** [comment]
@HardeepAsrani we can keep padding/margin but inherit the font specific size and related options. 

Otter should inherit the theme style not overwrite it.

**Comment by selul** [comment]
Also, not sure why we don't use the category in the same line as meta, i.e `<categroy>/<date> by <author>`?

**Comment by HardeepAsrani** [comment]
@selul That was a design decision, and I'm not sure if we should inherit the design styles for everything, especially size. Even themes have different heading sizes depending on where the heading is being used, like an H3 heading on the content vs H3 on widget title won't be same, nor will be H1 in a post vs H1 in site title. The default styles, specially font sizes, are for the content, and this isn't content.

If we don't give basic design/styles then it won't be used for most themes. We should have basic styles & themes that can enhance that if they want, but it should still look good by default.

**Comment by ineagu** [comment]
my 2c: I was thinking about this in the past and I do think is a challenging problem, limiting the whole site design by 6 sizes for headings can be tricky and I am sure there are themes not styling or using a weird styling for those.

For the approach, I believe at the end is plugin vs theme. If we keep the plugin clean by default and inheriting styles, it would make it easy to work with for theme developers or developers in general, but end users would get annoyed because it would look bad with a lot of themes and more important a particular design won't be the same on all themes, which is annoying.

But @selul why not have both like: Elementor: 1) By default have nice otter style that would assure the block looks great no-matter the theme + add an option to "disable otter styles" and inherit the style as much as possible, test with 5-6 top themes to make sure it looks decently good ( h2+h6 or H1+H5 or H2+span, etc). Then our themes can disable the style by default and we can allow other themes to define this (" that the theme recommend to disable the default styling")

For the 6 sizes thing, I don't have much insights into, if we should define a x list of design sizes/styles in the theme that can be then inherited in the whole site design ( might be interesting) or the 6 sizes everywhere can work.
