### ISSUE TITLE
Tabs Block

### ISSUE THREAD

**Issue by selul** [Codeinwp/gutenberg-blocks#268]
We can consider building a tabs block which will help improve the quality and complexity of the teamplates/sites that we build for gutenberg

**Comment by HardeepAsrani** [comment]
- Add AMP Support: https://amp.dev/documentation/examples/style-layout/tab_panels_with_amp-selector/

**Comment by JohnPixle** [comment]
- [Gutenberg Hub](https://gutenberghub.com/blocks/tabs-block/) highlights how the Tabs block works by Kadence. Very good reference.
- An execution by [Kioken blocks](https://kiokengutenberg.com/blocks/tabs-block/)

Thanks! ✌🏻

**Comment by mghenciu** [comment]
@HardeepAsrani , we don't use that a lot on our demos, since we knew it wasn't possible on Gutenberg (but this is just our experience).
And overall I think it's a useful component. For example in pages like this one: https://demosites.io/music-band/music-band-single-album/

![image](https://user-images.githubusercontent.com/52494172/118236048-462b3000-b49e-11eb-9caf-eb0cdefb3d2b.png)

**Comment by HardeepAsrani** [comment]
Thanks @mghenciu! Can you take this up @Soare-Robert-Daniel? Make sure they're AMP compatible. We can maybe use amp-accordion component for AMP to make tabbed component.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I do not know if I can make them AMP compatible. At the first look, the block has some complexity if we want to enable more content other than text.

The content part needs to have an `InnerBlock`. Also, even the `amp-component` needs [javascript](https://amp.dev/documentation/components/amp-accordion-v1.0/?format=websites).

**Comment by HardeepAsrani** [comment]
You can complete the rest first, we will take a look at AMP part then on.

**Comment by HardeepAsrani** [comment]
@mghenciu Should it be look like Tabs in mobile devices or like Accordion?
