### ISSUE TITLE
 Slider not displayed in AMP with Vertical Alignment in Section

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#375]
Ref: https://wordpress.org/support/topic/slider-not-displayed-on-mobile-view-after-changing-section-align/#post-13098506

Slider doesn't appear when used inside a Section block with Vertical Alignment. It only happens in AMP.

**Comment by HardeepAsrani** [comment]
@cosmin-serbanescu Can you try to fix it with CSS? I've tried a lot of seems hard without changing the CSS of the Section block. :(

**Comment by cosmin-serbanescu** [comment]
@HardeepAsrani couldn't find the root cause of this, most likely it's in the way AMP accordion works but you can fix it by making the `.wp-block-themeisle-blocks-advanced-columns.has-vertical-center .innerblocks-wrap` loose that align-items: center once it collapses (<=600px). It makes no sense in keeping it in the first place on mobile.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you update the PR with Cosmin's suggestions?

**Comment by Soare-Robert-Daniel** [comment]
Done it.
