### ISSUE TITLE
Section Outlining

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#45]
A better way to know which section is selected, preferably as a state.

**Comment by HardeepAsrani** [comment]
Closing as wontfix as this doesn't look good and isn't helpful at all.

**Comment by ineagu** [comment]
for me this still works different and a bit worse than what UAGG does.

**Comment by HardeepAsrani** [comment]
@ineagu I personally think UAG's border is too prominent and it takes away focus from the editor. What do you think @radu-themeisle @cosmin-serbanescu @selul

**Comment by radu-themeisle** [comment]
IMO the idea is good but the dotted border looks like we're trying too much. I also don't like UAG's approach as you get a lot of borders and looks crowded.
http://prntscr.com/mw7quw

There seems to be a transition in the size of the dotted border which doesn't look ok: https://www.useloom.com/share/11fc485a00744188bd3485680698a656
It's visible when you move the mouse out of the section, hope you can see it in the recording.

I would keep only the solid border when hovering or focused, this way the editor remains as simple and clean as possible. In the end our goal, I believe, is to have a clean editing interface so that it looks as close as possible to what they'll get on the front end. So "clean & clear" should be the way to go 🙂
http://prntscr.com/mw7t8u

**Comment by HardeepAsrani** [comment]
@ineagu @selul Thoughts?

**Comment by selul** [comment]
@radu-themeisle has a valid point, i think it is a good start

**Comment by HardeepAsrani** [comment]
So we're keeping the border, for now, I suppose?
