### ISSUE TITLE
Test with WordPress 5.8 Beta 1

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#701]
Hey @irinelenache,

Can you test the plugin with WordPress 5.8 Beta 1 to see if there are any breaking changes? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani I tried testing with wp 5.8 beta 2:

- [ ] When i try to open Otter settings in dashboard, nothing is showing and i get these errors in console https://vertis.d.pr/8xEJ27
- [ ] Can't find the otter blocks in editor, don't know if it's caused by the first problem

You can check here:
```
https://secure-swiftlet.jurassic.ninja
demo
cWbQpCpHmk8C
```

**Comment by HardeepAsrani** [comment]
@irinelenache Make sure you use the development branch of otter-blocks.

**Comment by HardeepAsrani** [comment]
You can do this along side https://github.com/Codeinwp/gutenberg-blocks/pull/706

**Comment by irinelenache** [comment]
@HardeepAsrani i tested with development branch of otter and this [PR](https://github.com/Codeinwp/gutenberg-blocks/pull/706) of gutenberg-blocks 

- [ ] The circle counter block doesn't work in front-end https://vertis.d.pr/G0DIo3
- [ ] ^ Same for progress bar
- [ ] The **Controls** settings in the Maps block look like this https://vertis.d.pr/ySho84
- [ ] When i add a Marker in the Maps block, if i click the marker, i get an error. Same happens when i try to edit the marker from the block settings.
https://www.loom.com/share/1a13c6fedc0f47c690fd42f1e90bf8ef

Will come back after testing more

**Comment by HardeepAsrani** [comment]
> The circle counter block doesn't work in front-end https://vertis.d.pr/G0DIo3

@Soare-Robert-Daniel Can you take a look at this? It's related to the core-js/runtime issue. I was able to fix it by including runtime in frontend scripts but that makes front-end files really bigger. Do you have any other alternative idea?

**Comment by Soare-Robert-Daniel** [comment]
> > The circle counter block doesn't work in front-end https://vertis.d.pr/G0DIo3
> 
> @Soare-Robert-Daniel Can you take a look at this? It's related to the core-js/runtime issue. I was able to fix it by including runtime in frontend scripts but that makes front-end files really bigger. Do you have any other alternative idea?

A trick is to use the version provided by WordPress.
Something like this:
```
	'regenerator-runtime/runtime.js': 'window.runtime',
	'core-js': 'window.core'
```
Check: #708

**Comment by HardeepAsrani** [comment]
I tested the #708 and it doesn't work for me, either in the backend or frontend. Any ideas?
