### ISSUE TITLE
Business Hours Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#733]
As the title says, business hours block. Part of #1451. This doesn't need to have a timing field but a text field so the user can put timing or just words there, like "24 Hours" or "Holiday."

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, @mghenciu, do you have some examples or references for this? Both mobile and desktop?

**Comment by HardeepAsrani** [comment]
Few examples:
- https://exclusiveaddons.com/wp-content/uploads/2020/11/Business-Hours-Widget@1x-1050x591.jpg
- https://cdn.powerpackelements.com/wp-content/uploads/2020/04/business-hour-img-5a.png
- https://demos.thememasters.club/wp-content/uploads/2020/06/business-hours.png

It should be a straightforward block, nothing fancy.

@mghenciu Any requirements from your side?

**Comment by mghenciu** [comment]
I also PM'd Robert with some examples.
I would also approach this incrementally, in terms of design options.

Things to keep in mind:
- time formats (24 hours vs 12 hours)
- week days should have the option to be edited, enabled/disabled. That's because some customers may want to use only 3 rows instead of 7: 
![image](https://user-images.githubusercontent.com/52494172/126328979-93d0ddf3-e1c1-4dd2-899b-d682b002844e.png)
- for starters I think having the line-separator between the Days/Rows, should be enough. Maybe we can go for another striped layout. But for sure we don't need bg-color customization for each day, at this point.
- I think the boxed layout, with bg-color, shadows, border radius, can be achieved using a column and placing the Business Hours block inside.  So make sure this works as expected.
- we should have alignment options for each column, as well for the Heading

**Comment by HardeepAsrani** [comment]
@mghenciu I saw some examples and we don't have to really give a time option. It can be a text field and people can write whatever they want, like "9AM to 5PM" or "Alternative Days" or whatever they want.

It only makes sense having a proper time option if one is dealing with different timezones which stores usually don't.

**Comment by mghenciu** [comment]
> @mghenciu I saw some examples and we don't have to really give a time option. It can be a text field and people can write whatever they want, like "9AM to 5PM" or "Alternative Days" or whatever they want.
> 
> It only makes sense having a proper time option if one is dealing with different timezones which stores usually don't.

If it's text, then it should be fine. 
I thought it's a predefined datetime type, or something like that.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel @irinelenache Can you review this? This block is included in this PR: https://github.com/Codeinwp/gutenberg-blocks/pull/741

**Comment by irinelenache** [comment]
@HardeepAsrani Just tested it, nice work 🚀 , found only some small things:

- [ ] The background color is visible in the bottom corners, i don't know if this is expected https://vertis.d.pr/KloMDh
- [ ] The separator inherits the background color https://vertis.d.pr/gAKiqq
- [ ] If i add separators between Business hours items and the style is set to Black and White, the items background isn't alternated anymore https://vertis.d.pr/AuXYK5

**Comment by HardeepAsrani** [comment]
@irinelenache Can you share the attributes you're using for the first issue so I could reproduce?

**Comment by irinelenache** [comment]
@HardeepAsrani Sure. 
https://vertis.d.pr/wWVmhp

**Comment by HardeepAsrani** [comment]
@irinelenache Should be fine now. Can you confirm?

**Comment by irinelenache** [comment]
@HardeepAsrani I marked as done the fixed issues 🚀 
Only this one is still happening:

> If i add separators between Business hours items and the style is set to Black and White, the items background isn't alternated anymore https://vertis.d.pr/AuXYK5

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache. I've fixed that too. Closing this as everything seems good to go. Thank you for the help!
