### ISSUE TITLE
Countdown Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#737]
A countdown block or extension to turn anything into a countdown, whichever suits best.

**Comment by Soare-Robert-Daniel** [comment]
How does this look exactly?  Is it a block where you just put a deadline, and it shows how much time you have until that date? Do you have a good idea about the design, something like [this](https://www.themeum.com/add-countdown-timer-wordpress/)?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It's exactly like what you add in the link. @mghenciu Let Robert know if you have anything particular in mind based on the use cases we have for the demo sites.

**Comment by mghenciu** [comment]
I don't have something specific in mind, as we only used Counter module in Elementor. But usually this goes on homepages/landing pages and it has a bold look & feel.

From a quick research here are a few things that may be interesting (besides the base functionalities):
- have the option to chose what to display (only the days + hours, or days + hours + minutes + seconds)
- have the options to choose what happens when the countdown finishes. For starters I think we can go for **Restart the countdown** and/or **redirect** when the countdown ends
- maybe, it makes more sense to skip the Templates part for the fist version, and have only the shape controls that will allow a few design variations. By shape controls I am referring to the option to have a background color (it can also be transparent), border settings including border radius, which should allow users to create circular designs:
![image](https://user-images.githubusercontent.com/52494172/126292339-3e8cb273-dbc7-4837-9cd7-d86ccba8bedd.png)
