### ISSUE TITLE
Redesign Post Grid Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#76]
We need to redo Post Grid Block to make it more advanced. More details coming after 1.2.0 release.

**Comment by HardeepAsrani** [comment]
@radu-themeisle and @stefan-cotitosu We need to get this tested. We've re-did the Post Grid block, and renamed it to Posts block.

It has added a few options, such as the Image Size option. And most importantly, it has added an option to re-arrange the layout of posts.

And once again, backward-compatibility is very very important so let me know if it breaks if you update it from an older version.

I've sent you the link to the zip.

**Comment by radu-themeisle** [comment]
Hey,

Updating doesn't break anything, the only thing I spotted was that the excerpt length changed from 200 to 100 but maybe because I didn't change it so it was the default.

For this part: http://prntscr.com/n4pzbb

- Do you think it's possible to replace the pointer that shows when you move around the meta to a hand (https://fontawesome.com/v4.7.0/icon/hand-rock-o)
- I'd disable hover color for "Featured Image" as you can't do anything with it (apart from disabling it)
- If it's possible, enable drag&drop on the whole button width (the hamburger icon and the description) up until the enable/disable icon. It would make it easier for users to use it.
- If you can make the above point, then I would suggest changing the cursor to pointer on hover so it suggests better that you can interact with the tab
- Can you make the hamburger icon's color darker to match the eye icon color? It would improve the visibility of it.

For this part: http://prntscr.com/n4q43r
- I'd move the the two options under Settings, right before the number of columns. It seems too much to have a separate menu just for 1 option.
- I'd also use simpler images to show the layout (like the ones we use in Hestia or Neve)
- If you click on one of the layouts and then click outside of it they lose the blue border color, it turns to black. It should keep the blue color to avoid confusion.
- The grey background color when you hover over the layouts can be a bit darker, it's fairly visible. Also, make the active layout keep the background color, now it doesn't have a background color and you can hover over it and see the grey background color.

**Comment by HardeepAsrani** [comment]
> Do you think it's possible to replace the pointer that shows when you move around the meta to a hand (https://fontawesome.com/v4.7.0/icon/hand-rock-o)

We don't use custom icons but CSS cursor property. We can use any of these icons, you can pick: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Values - `grab` and `grabbing` do it?

> I'd disable hover color for "Featured Image" as you can't do anything with it (apart from disabling it)

Makes sense. Will do.

> If it's possible, enable drag&drop on the whole button width (the hamburger icon and the description) up until the enable/disable icon. It would make it easier for users to use it.

That was the plan but if we do that, we can't click over the Visibility icons because of how this library for drag & drop feature works, so that's why I had to make this compromise. 😞 

> Can you make the hamburger icon's color darker to match the eye icon color? It would improve the visibility of it.

Alrighty.

> I'd move the the two options under Settings, right before the number of columns. It seems too much to have a separate menu just for 1 option.

We've made it like this because that's how this looks if you use Block Styles with Gutenberg:

<img width="536" alt="Screen Shot 2019-03-30 at 3 28 45 AM" src="https://user-images.githubusercontent.com/2649903/55264885-f4ae8f80-529b-11e9-8e03-23881f1dc292.png">

> I'd also use simpler images to show the layout (like the ones we use in Hestia or Neve)

Normally real images show in Gutenberg so black and white will look weird, so that's why kept it like this. Can change if future if needed. Don't want to disturb Cosmin again. 😛 

> If you click on one of the layouts and then click outside of it they lose the blue border color, it turns to black. It should keep the blue color to avoid confusion.

Actually it should keep black border. Black border is for the selected one, and blue border is when you focus over an element.

Now, in a sane world, this shouldn't be confusing but that's how it is with default Gutenberg blocks so we've copied the same time. This is weird but that's Gutenberg. 😆 

> The grey background color when you hover over the layouts can be a bit darker, it's fairly visible. Also, make the active layout keep the background color, now it doesn't have a background color and you can hover over it and see the grey background color.

I know what you mean...but that's how default Gutenberg layout looks so kept it that way. They followed a design-first approached and somehow made these terrible decisions. _sigh_

**Comment by HardeepAsrani** [comment]
Closing this. We can continue the discussion regardless.

**Comment by radu-themeisle** [comment]
> We can use any of these icons, you can pick: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Values - grab and grabbing do it?
Yep, they're perfect

> Normally real images show in Gutenberg[...] Don't want to disturb Cosmin again. 
I can also help with small Photoshop tasks / icons / vector images, just ask 🙂

> followed a design-first approached and somehow made these terrible decisions
boo 👎 for their bad decisions
