### ISSUE TITLE
Redesign Google Map Block

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-blocks#77]
We need to redo Google Map Block to make it more advanced. More details coming after 1.2.0 release.

**Comment by HardeepAsrani** [comment]
@radu-themeisle and @stefan-cotitosu, we need to test Google Map block. Below are the download links and also a link of a video which shows you everything you need to know before reviewing the block.

Make sure your Google Maps API has Maps and Places enabled. Let know if you find any issues, including backward compatibilities.

Download latest version: https://ufile.io/3m7py

Video to guide you about new features: https://www.useloom.com/share/00f797469f5a4ea1964b5601b5eab6f5

**Comment by radu-themeisle** [comment]
Hey @HardeepAsrani, managed to test out the G Block and here are my thoughts:

- bug: If I delete the zoom value I get an error, we should revert in the back to the default value: http://prntscr.com/mzhyyu

**Updating to new version**: https://www.useloom.com/share/6acc8b7a74654ca98fa9606a2063a9b7
- Maps don't remember the location
- on the second try, the one in the video I got the "only for development purposes" message (this is how it looks before updating: http://prntscr.com/mzj8tn). I've read that this is due to G changing their terms and charging for Maps, but why do they work now?...
- I took a look at Elementor and their widget doesn't require an API, can't we do the same and workaround the API?
- Regarding the API, I can't remember now where I saw this but we should integrate it, when you don't have one or if you delete the current one we should show a link to the G Maps API (I think [here](https://console.developers.google.com/apis/credentials))
- there's no more space between widgets
- the second row has a 2 column section which lost its height properties (I'm not sure if it also lost the width, I couldn't spot visually a difference)
- Rolling back the version: the second row doesn't recover it's height settings

Some thoughts about the new UI:
- If I click a tab (and remains focused) the background-color on hover doesn't work anymore even after the tab is closed (might be something from Chrome, didn't try it out with Firefox): https://www.useloom.com/share/a4c4b8ce3cf847bba426b5af215c3f73
- I'd integrate the Latitude/Longitude in the Location input. This will free up space  and simplify the UI as I don't see the point in having both Location and coordinates, logically you'd use one or the other, so let's make them 2 in 1 🙂.
- Put Location field under Positioning & Zooming, (Location = Positioning), plus Map Type will be more visible as I believe it should as visible as possible
zoom level 0-20: 0 = http://prntscr.com/mzhx9l; default to 15
- Map height: limit it to 800 (or the highest "normal" screen), there's no point in having a slider span that much in height, there's no use case and because the range is huge the visual feedback of the slider moving very little if you use the arrows (from keyboard or input) is barely visible
- Controls: move the slider to the right, it will create a "box" and make the section look "aligned": http://prntscr.com/mzk4vh
- Controls: I'm not pretty sure what they do because the maps are not enabled, but once we fix that maybe we can better explain what they do. I have a guess about what they do but I want to wait until I try them out.
- Markers: Merge Latitude/Longitude with Location (same as before): http://prntscr.com/mzk0p6
- Marker tabs: An idea would be to replace the "x" with a carret/angle that would better point out that the tabs can open. We can move the "X's" inside the tab and make the red to stand out http://prntscr.com/mzk39c
- Marker tabs: Make the active one keep the "darker" color from hover: http://prntscr.com/mzk4ac
- Marker tabs: make their border-radius the same as the inputs (4px) to keep a consistent look, but I'm guessing the inputs take their 4px border-radius from Neve...: http://prntscr.com/mzk7to
- Custom Markers (crazy idea, maybe for later): enable picking a color

- There are some weird lines: http://prntscr.com/mzk23s; rolling back I don't see them: http://prntscr.com/mzkd61

**Comment by HardeepAsrani** [comment]
> bug: If I delete the zoom value I get an error, we should revert in the back to the default value: http://prntscr.com/mzhyyu

- It's an issue with the older version so no need to worry about it.

> If I click a tab (and remains focused) the background-color on hover doesn't work anymore even after the tab is closed (might be something from Chrome, didn't try it out with Firefox): https://www.useloom.com/share/a4c4b8ce3cf847bba426b5af215c3f73

- That's an issue with Gutenberg so nothing we can do.

> I'd integrate the Latitude/Longitude in the Location input. This will free up space and simplify the UI as I don't see the point in having both Location and coordinates, logically you'd use one or the other, so let's make them 2 in 1 🙂.

I also wanted to do that but Google Maps event wanted something else, so that's why it's the way it is.

> Put Location field under Positioning & Zooming, (Location = Positioning), plus Map Type will be more visible as I believe it should as visible as possible

The location field is the field anyone who has added a block will setup first, so that's why it's on top.

> zoom level 0-20: 0 = http://prntscr.com/mzhx9l; default to 15

I don't understand. Can you explain this one?

> Map height: limit it to 800 (or the highest "normal" screen), there's no point in having a slider span that much in height, there's no use case and because the range is huge the visual feedback of the slider moving very little if you use the arrows (from keyboard or input) is barely visible

Makes sense but limit it to 1400 as 800 can be small for a full page map.

> Controls: move the slider to the right, it will create a "box" and make the section look "aligned": http://prntscr.com/mzk4vh

Can't change, Gutenberg UI,

> Markers: Merge Latitude/Longitude with Location (same as before): http://prntscr.com/mzk0p6

Same reason as before. :)

> Marker tabs: An idea would be to replace the "x" with a the /angle that would better point out that the tabs can open. We can move the "X's" inside the tab and make the red to stand out http://prntscr.com/mzk39c

Alright, we can do that.

> Marker tabs: Make the active one keep the "darker" color from hover: http://prntscr.com/mzk4ac

That will make it look different from Gutenberg's Panel UI.

> Custom Markers (crazy idea, maybe for later): enable picking a color

I actually left it for future too, if more people request. 😄 

> There are some weird lines: http://prntscr.com/mzk23s; rolling back I don't see them: http://prntscr.com/mzkd61

I don't think it's because of us. Couldn't reproduce.

**Comment by HardeepAsrani** [comment]
@radu-themeisle You need to have Google Maps API + Google Places API for it. I've sent mine on Slack for you to test and you won't face any issues.

**Comment by HardeepAsrani** [comment]
> I took a look at Elementor and their widget doesn't require an API, can't we do the same and workaround the API?

They use Google Map's Embed API which doesn't allow things like markers, but only to show the location. That's why.

**Comment by HardeepAsrani** [comment]
> on the second try, the one in the video I got the "only for development purposes" message (this is how it looks before updating: http://prntscr.com/mzj8tn). I've read that this is due to G changing their terms and charging for Maps, but why do they work now?...

This happens when your Google Maps API isn't right. I've sent you an API to test on Slack so maybe you can try that out and see if it works?

**Comment by radu-themeisle** [comment]
> _zoom level 0-20: 0 = http://prntscr.com/mzhx9l; default to 15_
> 
> I don't understand. Can you explain this one?

I took this idea from Elementor and made sense to me but looking over it again it doesn't seem that important. They use a default zoom value of 15 which shows the map zoomed in at at pretty ok level, rather than seeing the whole world by default. In Elementor's case most times I don't even change the zoom level as the default one is good enough.

> _Map height: limit it to 800 (or the highest "normal" screen)_
> 
> Makes sense but limit it to 1400

ok for 1400 👍 

> _Marker tabs: An idea would be to replace the "x" with a carret/angle_
> 
> I love the idea but that will add one extra step to remove the marker

I see your point, I don't think it's such a problem as I believe people spend more time editing a marker (to position it right or change details) than deleting one. We can ask for a second opinion if you want.

> _Marker tabs: Make the active one keep the "darker" color from hover_
> 
> That will make it look different from Gutenberg's Panel UI.

ok

> There are some weird lines

I think it might be Local causing the issue

> _on the second try, the one in the video I got the "only for development purposes" message_
> 
> This happens when your Google Maps API isn't right

Seems weird that rolling back works, but I guess users will have to adhere to Google's T&C and pay for the API sooner or later so might be no point in pursuing why rolling back makes the block work.

**Comment by radu-themeisle** [comment]
I tested the Controls after you gave me the API.
The only weird thing I found is that if you disable the Zoom Controls, you can still use Ctrl+scroll to zoom. I think that should also be disabled, otherwise there's no point in having the ability to deactivate zooming.

I don't really see the point in having the option to disable those controls if we don't see users asking explicitly for them. Maybe we can add them later if we see users taking interest in them?

**Comment by HardeepAsrani** [comment]
> Seems weird that rolling back works, but I guess users will have to adhere to Google's T&C and pay for the API sooner or later so might be no point in pursuing why rolling back makes the block work.

The old block just used Google's Map API. The new one uses Map + Places API. The places API is for the search part.

> I don't really see the point in having the option to disable those controls if we don't see users asking explicitly for them. Maybe we can add them later if we see users taking interest in them?

We have added it so people using Intergeo can make the switch easily.

> The only weird thing I found is that if you disable the Zoom Controls, you can still use Ctrl+scroll to zoom. I think that should also be disabled, otherwise there's no point in having the ability to deactivate zooming.

I have disabled it the way Google defines but I'll see if there's something I can do about it.

**Comment by HardeepAsrani** [comment]
@radu-themeisle I've made the transition better. Now if you are coming from old API then the map in back will say that you need to have the Places API visible.

One pain point is that you can't change Google Map API once it's loaded. If you change it, you will have to reload the page.

Anyway, I've committed the changes and I'll ask you to retest it later when next update is ready, as there's nothing new to test right now.

Just one thing, if you remove the transition from old version part, is everything working properly?

**Comment by radu-themeisle** [comment]
> Just one thing, if you remove the transition from old version part, is everything working properly?

You mean if I use a fresh install of Otter? I don't understand what you mean by _transition from old version part_ 😞

**Comment by HardeepAsrani** [comment]
@radu-themeisle I mean if you add a new block.

**Comment by radu-themeisle** [comment]
@HardeepAsrani yes, everything works properly

**Comment by HardeepAsrani** [comment]
Thank you good sir @radu-themeisle
